### ISSUE TITLE
error: expected expression __HAL_TIM_SET_CAPTUREPOLARITY(__HANDLE__, __CHANNEL__, __POLARITY__)  

### ISSUE THREAD

**Issue by ZhaoYandong00** [STMicroelectronics/STM32CubeF1#21] opened 2020-08-19 06:13 UTC
When I use the function, I find MDK_ARM reports an error(error: expected expression ).Review the function,I find that  this function( TIM_RESET_CAPTUREPOLARITY ) uses  an extra ')`.

**Comment by ASELSTM** [comment] 2020-08-19 16:04
Hi @ZhaoYandong00, 

Thank you for your contribution.

Actually, the point you raised is already known. It has been internally fixed. The fix will be published in the frame of a future publication.

With regards,

**Comment by ALABSTM** [comment] 2020-10-13 08:25
ST Internal Reference: 80370

**Comment by ALABSTM** [comment] 2020-10-13 08:25
Duplicate of #18.

**Closed as completed** 2020-10-13 08:26 UTC
Labels: bug, duplicate, spotted before customer, hal
